# Generated by Django 2.1.11 on 2020-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count1', models.IntegerField()),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50)),
                ('confirmedCases', models.CharField(max_length=50)),
                ('curedCases', models.CharField(max_length=50)),
                ('deathCases', models.CharField(max_length=50)),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.IntegerField()),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
